#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tickets2")]
	public partial class dcTicketsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdministrador(Administrador instance);
    partial void UpdateAdministrador(Administrador instance);
    partial void DeleteAdministrador(Administrador instance);
    partial void InsertCatCategoria(CatCategoria instance);
    partial void UpdateCatCategoria(CatCategoria instance);
    partial void DeleteCatCategoria(CatCategoria instance);
    partial void InsertCatServicio(CatServicio instance);
    partial void UpdateCatServicio(CatServicio instance);
    partial void DeleteCatServicio(CatServicio instance);
    partial void InsertComentario(Comentario instance);
    partial void UpdateComentario(Comentario instance);
    partial void DeleteComentario(Comentario instance);
    partial void InsertComentario1(Comentario1 instance);
    partial void UpdateComentario1(Comentario1 instance);
    partial void DeleteComentario1(Comentario1 instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertServicio(Servicio instance);
    partial void UpdateServicio(Servicio instance);
    partial void DeleteServicio(Servicio instance);
    partial void InsertServicioEstado(ServicioEstado instance);
    partial void UpdateServicioEstado(ServicioEstado instance);
    partial void DeleteServicioEstado(ServicioEstado instance);
    partial void InsertServTipoCat(ServTipoCat instance);
    partial void UpdateServTipoCat(ServTipoCat instance);
    partial void DeleteServTipoCat(ServTipoCat instance);
    partial void InsertTrabajador(Trabajador instance);
    partial void UpdateTrabajador(Trabajador instance);
    partial void DeleteTrabajador(Trabajador instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public dcTicketsDataContext() : 
				base(global::Datos.Properties.Settings.Default.Tickets2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrador> Administradors
		{
			get
			{
				return this.GetTable<Administrador>();
			}
		}
		
		public System.Data.Linq.Table<CatCategoria> CatCategorias
		{
			get
			{
				return this.GetTable<CatCategoria>();
			}
		}
		
		public System.Data.Linq.Table<CatServicio> CatServicios
		{
			get
			{
				return this.GetTable<CatServicio>();
			}
		}
		
		public System.Data.Linq.Table<Comentario> Comentarios
		{
			get
			{
				return this.GetTable<Comentario>();
			}
		}
		
		public System.Data.Linq.Table<Comentario1> Comentarios1
		{
			get
			{
				return this.GetTable<Comentario1>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamentos
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Encuesta> Encuestas
		{
			get
			{
				return this.GetTable<Encuesta>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Personas
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Servicio> Servicios
		{
			get
			{
				return this.GetTable<Servicio>();
			}
		}
		
		public System.Data.Linq.Table<ServicioEstado> ServicioEstados
		{
			get
			{
				return this.GetTable<ServicioEstado>();
			}
		}
		
		public System.Data.Linq.Table<ServTipoCat> ServTipoCats
		{
			get
			{
				return this.GetTable<ServTipoCat>();
			}
		}
		
		public System.Data.Linq.Table<Trabajador> Trabajadors
		{
			get
			{
				return this.GetTable<Trabajador>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosAsignados")]
		public ISingleResult<sp_Get_ServiciosAsignadosResult> sp_Get_ServiciosAsignados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosAsignadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosAsignadosM")]
		public ISingleResult<sp_Get_ServiciosAsignadosMResult> sp_Get_ServiciosAsignadosM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosAsignadosMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosFinalizados")]
		public ISingleResult<sp_Get_ServiciosFinalizadosResult> sp_Get_ServiciosFinalizados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosFinalizadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosFinalizadosM")]
		public ISingleResult<sp_Get_ServiciosFinalizadosMResult> sp_Get_ServiciosFinalizadosM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosFinalizadosMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosSolicitados")]
		public ISingleResult<sp_Get_ServiciosSolicitadosResult> sp_Get_ServiciosSolicitados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosSolicitadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosSolicitadosM")]
		public ISingleResult<sp_Get_ServiciosSolicitadosMResult> sp_Get_ServiciosSolicitadosM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosSolicitadosMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spTicketsConsulta")]
		public ISingleResult<spTicketsConsultaResult> spTicketsConsulta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string filtro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fol, page, pageSize, filtro, tipo);
			return ((ISingleResult<spTicketsConsultaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spTicketsConsultaManto")]
		public ISingleResult<spTicketsConsultaMantoResult> spTicketsConsultaManto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string filtro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fol, page, pageSize, filtro, tipo);
			return ((ISingleResult<spTicketsConsultaMantoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrador")]
	public partial class Administrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Adm_ID;
		
		private int _Per_ID;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdm_IDChanging(int value);
    partial void OnAdm_IDChanged();
    partial void OnPer_IDChanging(int value);
    partial void OnPer_IDChanged();
    #endregion
		
		public Administrador()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="adm_ID", Storage="_Adm_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Adm_ID
		{
			get
			{
				return this._Adm_ID;
			}
			set
			{
				if ((this._Adm_ID != value))
				{
					this.OnAdm_IDChanging(value);
					this.SendPropertyChanging();
					this._Adm_ID = value;
					this.SendPropertyChanged("Adm_ID");
					this.OnAdm_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID", Storage="_Per_ID", DbType="Int NOT NULL")]
		public int Per_ID
		{
			get
			{
				return this._Per_ID;
			}
			set
			{
				if ((this._Per_ID != value))
				{
					this.OnPer_IDChanging(value);
					this.SendPropertyChanging();
					this._Per_ID = value;
					this.SendPropertyChanged("Per_ID");
					this.OnPer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Administrador", Storage="_Persona", ThisKey="Per_ID", OtherKey="Per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Administradors.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Administradors.Add(this);
						this._Per_ID = value.Per_ID;
					}
					else
					{
						this._Per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatCategorias")]
	public partial class CatCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdServ;
		
		private string _TipoCate;
		
		private System.Nullable<bool> _Estatus;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdServChanging(System.Nullable<int> value);
    partial void OnIdServChanged();
    partial void OnTipoCateChanging(string value);
    partial void OnTipoCateChanged();
    partial void OnEstatusChanging(System.Nullable<bool> value);
    partial void OnEstatusChanged();
    #endregion
		
		public CatCategoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="idServ", Storage="_IdServ", DbType="Int")]
		public System.Nullable<int> IdServ
		{
			get
			{
				return this._IdServ;
			}
			set
			{
				if ((this._IdServ != value))
				{
					this.OnIdServChanging(value);
					this.SendPropertyChanging();
					this._IdServ = value;
					this.SendPropertyChanged("IdServ");
					this.OnIdServChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCate", DbType="VarChar(20)")]
		public string TipoCate
		{
			get
			{
				return this._TipoCate;
			}
			set
			{
				if ((this._TipoCate != value))
				{
					this.OnTipoCateChanging(value);
					this.SendPropertyChanging();
					this._TipoCate = value;
					this.SendPropertyChanged("TipoCate");
					this.OnTipoCateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="estatus", Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatServicios")]
	public partial class CatServicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TipoServ;
		
		private System.Nullable<bool> _Estatus;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTipoServChanging(string value);
    partial void OnTipoServChanged();
    partial void OnEstatusChanging(System.Nullable<bool> value);
    partial void OnEstatusChanged();
    #endregion
		
		public CatServicio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoServ", DbType="VarChar(20)")]
		public string TipoServ
		{
			get
			{
				return this._TipoServ;
			}
			set
			{
				if ((this._TipoServ != value))
				{
					this.OnTipoServChanging(value);
					this.SendPropertyChanging();
					this._TipoServ = value;
					this.SendPropertyChanged("TipoServ");
					this.OnTipoServChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="estatus", Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentario")]
	public partial class Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Com_ID;
		
		private int _Ser_ID;
		
		private string _Com_Comentario;
		
		private System.DateTime _Com_FechaCom;
		
		private int _Per_ID;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Servicio> _Servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCom_IDChanging(int value);
    partial void OnCom_IDChanged();
    partial void OnSer_IDChanging(int value);
    partial void OnSer_IDChanged();
    partial void OnCom_ComentarioChanging(string value);
    partial void OnCom_ComentarioChanged();
    partial void OnCom_FechaComChanging(System.DateTime value);
    partial void OnCom_FechaComChanged();
    partial void OnPer_IDChanging(int value);
    partial void OnPer_IDChanged();
    #endregion
		
		public Comentario()
		{
			this._Persona = default(EntityRef<Persona>);
			this._Servicio = default(EntityRef<Servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="com_ID", Storage="_Com_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Com_ID
		{
			get
			{
				return this._Com_ID;
			}
			set
			{
				if ((this._Com_ID != value))
				{
					this.OnCom_IDChanging(value);
					this.SendPropertyChanging();
					this._Com_ID = value;
					this.SendPropertyChanged("Com_ID");
					this.OnCom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_ID", Storage="_Ser_ID", DbType="Int NOT NULL")]
		public int Ser_ID
		{
			get
			{
				return this._Ser_ID;
			}
			set
			{
				if ((this._Ser_ID != value))
				{
					this.OnSer_IDChanging(value);
					this.SendPropertyChanging();
					this._Ser_ID = value;
					this.SendPropertyChanged("Ser_ID");
					this.OnSer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="com_Comentario", Storage="_Com_Comentario", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Com_Comentario
		{
			get
			{
				return this._Com_Comentario;
			}
			set
			{
				if ((this._Com_Comentario != value))
				{
					this.OnCom_ComentarioChanging(value);
					this.SendPropertyChanging();
					this._Com_Comentario = value;
					this.SendPropertyChanged("Com_Comentario");
					this.OnCom_ComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="com_FechaCom", Storage="_Com_FechaCom", DbType="DateTime NOT NULL")]
		public System.DateTime Com_FechaCom
		{
			get
			{
				return this._Com_FechaCom;
			}
			set
			{
				if ((this._Com_FechaCom != value))
				{
					this.OnCom_FechaComChanging(value);
					this.SendPropertyChanging();
					this._Com_FechaCom = value;
					this.SendPropertyChanged("Com_FechaCom");
					this.OnCom_FechaComChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID", Storage="_Per_ID", DbType="Int NOT NULL")]
		public int Per_ID
		{
			get
			{
				return this._Per_ID;
			}
			set
			{
				if ((this._Per_ID != value))
				{
					this.OnPer_IDChanging(value);
					this.SendPropertyChanging();
					this._Per_ID = value;
					this.SendPropertyChanged("Per_ID");
					this.OnPer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Comentario", Storage="_Persona", ThisKey="Per_ID", OtherKey="Per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Comentarios.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Comentarios.Add(this);
						this._Per_ID = value.Per_ID;
					}
					else
					{
						this._Per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicio_Comentario", Storage="_Servicio", ThisKey="Ser_ID", OtherKey="Ser_ID", IsForeignKey=true)]
		public Servicio Servicio
		{
			get
			{
				return this._Servicio.Entity;
			}
			set
			{
				Servicio previousValue = this._Servicio.Entity;
				if (((previousValue != value) 
							|| (this._Servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicio.Entity = null;
						previousValue.Comentarios.Remove(this);
					}
					this._Servicio.Entity = value;
					if ((value != null))
					{
						value.Comentarios.Add(this);
						this._Ser_ID = value.Ser_ID;
					}
					else
					{
						this._Ser_ID = default(int);
					}
					this.SendPropertyChanged("Servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentarios")]
	public partial class Comentario1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Ser_ID;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Comentario;
		
		private System.Nullable<int> _Per_ID;
		
		private string _Tipo;
		
		private System.Nullable<bool> _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSer_IDChanging(System.Nullable<int> value);
    partial void OnSer_IDChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    partial void OnPer_IDChanging(System.Nullable<int> value);
    partial void OnPer_IDChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnEstadoChanging(System.Nullable<bool> value);
    partial void OnEstadoChanged();
    #endregion
		
		public Comentario1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_ID", Storage="_Ser_ID", DbType="Int")]
		public System.Nullable<int> Ser_ID
		{
			get
			{
				return this._Ser_ID;
			}
			set
			{
				if ((this._Ser_ID != value))
				{
					this.OnSer_IDChanging(value);
					this.SendPropertyChanging();
					this._Ser_ID = value;
					this.SendPropertyChanged("Ser_ID");
					this.OnSer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(500)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID", Storage="_Per_ID", DbType="Int")]
		public System.Nullable<int> Per_ID
		{
			get
			{
				return this._Per_ID;
			}
			set
			{
				if ((this._Per_ID != value))
				{
					this.OnPer_IDChanging(value);
					this.SendPropertyChanging();
					this._Per_ID = value;
					this.SendPropertyChanged("Per_ID");
					this.OnPer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Char(3)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Dep_ID;
		
		private string _Dep_Departamento;
		
		private bool _Dep_AtiendeServicios;
		
		private EntitySet<Persona> _Personas;
		
		private EntitySet<Servicio> _Servicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDep_IDChanging(int value);
    partial void OnDep_IDChanged();
    partial void OnDep_DepartamentoChanging(string value);
    partial void OnDep_DepartamentoChanged();
    partial void OnDep_AtiendeServiciosChanging(bool value);
    partial void OnDep_AtiendeServiciosChanged();
    #endregion
		
		public Departamento()
		{
			this._Personas = new EntitySet<Persona>(new Action<Persona>(this.attach_Personas), new Action<Persona>(this.detach_Personas));
			this._Servicios = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicios), new Action<Servicio>(this.detach_Servicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dep_ID", Storage="_Dep_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Dep_ID
		{
			get
			{
				return this._Dep_ID;
			}
			set
			{
				if ((this._Dep_ID != value))
				{
					this.OnDep_IDChanging(value);
					this.SendPropertyChanging();
					this._Dep_ID = value;
					this.SendPropertyChanged("Dep_ID");
					this.OnDep_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dep_Departamento", Storage="_Dep_Departamento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dep_Departamento
		{
			get
			{
				return this._Dep_Departamento;
			}
			set
			{
				if ((this._Dep_Departamento != value))
				{
					this.OnDep_DepartamentoChanging(value);
					this.SendPropertyChanging();
					this._Dep_Departamento = value;
					this.SendPropertyChanged("Dep_Departamento");
					this.OnDep_DepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dep_AtiendeServicios", Storage="_Dep_AtiendeServicios", DbType="Bit NOT NULL")]
		public bool Dep_AtiendeServicios
		{
			get
			{
				return this._Dep_AtiendeServicios;
			}
			set
			{
				if ((this._Dep_AtiendeServicios != value))
				{
					this.OnDep_AtiendeServiciosChanging(value);
					this.SendPropertyChanging();
					this._Dep_AtiendeServicios = value;
					this.SendPropertyChanged("Dep_AtiendeServicios");
					this.OnDep_AtiendeServiciosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Persona", Storage="_Personas", ThisKey="Dep_ID", OtherKey="Dep_ID")]
		public EntitySet<Persona> Personas
		{
			get
			{
				return this._Personas;
			}
			set
			{
				this._Personas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Servicio", Storage="_Servicios", ThisKey="Dep_ID", OtherKey="Ser_DeptoQueAtiende")]
		public EntitySet<Servicio> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personas(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Personas(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
		
		private void attach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Encuesta")]
	public partial class Encuesta
	{
		
		private System.Nullable<decimal> _Serv_Folio;
		
		private string _Serv_calidad;
		
		private string _Serv_tiempo;
		
		private string _Serv_atencion;
		
		private string _Serv_comentario;
		
		private System.Nullable<System.DateTime> _Serv_fecha;
		
		private string _Serv_hora;
		
		public Encuesta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serv_Folio", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Serv_Folio
		{
			get
			{
				return this._Serv_Folio;
			}
			set
			{
				if ((this._Serv_Folio != value))
				{
					this._Serv_Folio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serv_calidad", Storage="_Serv_calidad", DbType="Char(1)")]
		public string Serv_calidad
		{
			get
			{
				return this._Serv_calidad;
			}
			set
			{
				if ((this._Serv_calidad != value))
				{
					this._Serv_calidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serv_tiempo", Storage="_Serv_tiempo", DbType="Char(1)")]
		public string Serv_tiempo
		{
			get
			{
				return this._Serv_tiempo;
			}
			set
			{
				if ((this._Serv_tiempo != value))
				{
					this._Serv_tiempo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serv_atencion", Storage="_Serv_atencion", DbType="Char(1)")]
		public string Serv_atencion
		{
			get
			{
				return this._Serv_atencion;
			}
			set
			{
				if ((this._Serv_atencion != value))
				{
					this._Serv_atencion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serv_comentario", Storage="_Serv_comentario", DbType="Char(100)")]
		public string Serv_comentario
		{
			get
			{
				return this._Serv_comentario;
			}
			set
			{
				if ((this._Serv_comentario != value))
				{
					this._Serv_comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serv_fecha", Storage="_Serv_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Serv_fecha
		{
			get
			{
				return this._Serv_fecha;
			}
			set
			{
				if ((this._Serv_fecha != value))
				{
					this._Serv_fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="serv_hora", Storage="_Serv_hora", DbType="VarChar(20)")]
		public string Serv_hora
		{
			get
			{
				return this._Serv_hora;
			}
			set
			{
				if ((this._Serv_hora != value))
				{
					this._Serv_hora = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Per_ID;
		
		private string _Per_Nombre;
		
		private string _Per_ApePat;
		
		private string _Per_ApeMat;
		
		private string _Per_Email;
		
		private string _Per_ExtTelefono;
		
		private int _Dep_ID;
		
		private bool _Per_IsActivo;
		
		private string _Per_copia;
		
		private EntitySet<Administrador> _Administradors;
		
		private EntitySet<Comentario> _Comentarios;
		
		private EntitySet<Servicio> _Servicios;
		
		private EntitySet<Servicio> _Per_s;
		
		private EntitySet<Trabajador> _Trabajadors;
		
		private EntitySet<Usuario> _Usuarios;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPer_IDChanging(int value);
    partial void OnPer_IDChanged();
    partial void OnPer_NombreChanging(string value);
    partial void OnPer_NombreChanged();
    partial void OnPer_ApePatChanging(string value);
    partial void OnPer_ApePatChanged();
    partial void OnPer_ApeMatChanging(string value);
    partial void OnPer_ApeMatChanged();
    partial void OnPer_EmailChanging(string value);
    partial void OnPer_EmailChanged();
    partial void OnPer_ExtTelefonoChanging(string value);
    partial void OnPer_ExtTelefonoChanged();
    partial void OnDep_IDChanging(int value);
    partial void OnDep_IDChanged();
    partial void OnPer_IsActivoChanging(bool value);
    partial void OnPer_IsActivoChanged();
    partial void OnPer_copiaChanging(string value);
    partial void OnPer_copiaChanged();
    #endregion
		
		public Persona()
		{
			this._Administradors = new EntitySet<Administrador>(new Action<Administrador>(this.attach_Administradors), new Action<Administrador>(this.detach_Administradors));
			this._Comentarios = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentarios), new Action<Comentario>(this.detach_Comentarios));
			this._Servicios = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicios), new Action<Servicio>(this.detach_Servicios));
			this._Per_s = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Per_s), new Action<Servicio>(this.detach_Per_s));
			this._Trabajadors = new EntitySet<Trabajador>(new Action<Trabajador>(this.attach_Trabajadors), new Action<Trabajador>(this.detach_Trabajadors));
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID", Storage="_Per_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Per_ID
		{
			get
			{
				return this._Per_ID;
			}
			set
			{
				if ((this._Per_ID != value))
				{
					this.OnPer_IDChanging(value);
					this.SendPropertyChanging();
					this._Per_ID = value;
					this.SendPropertyChanged("Per_ID");
					this.OnPer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_Nombre", Storage="_Per_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Per_Nombre
		{
			get
			{
				return this._Per_Nombre;
			}
			set
			{
				if ((this._Per_Nombre != value))
				{
					this.OnPer_NombreChanging(value);
					this.SendPropertyChanging();
					this._Per_Nombre = value;
					this.SendPropertyChanged("Per_Nombre");
					this.OnPer_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ApePat", Storage="_Per_ApePat", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Per_ApePat
		{
			get
			{
				return this._Per_ApePat;
			}
			set
			{
				if ((this._Per_ApePat != value))
				{
					this.OnPer_ApePatChanging(value);
					this.SendPropertyChanging();
					this._Per_ApePat = value;
					this.SendPropertyChanged("Per_ApePat");
					this.OnPer_ApePatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ApeMat", Storage="_Per_ApeMat", DbType="VarChar(200)")]
		public string Per_ApeMat
		{
			get
			{
				return this._Per_ApeMat;
			}
			set
			{
				if ((this._Per_ApeMat != value))
				{
					this.OnPer_ApeMatChanging(value);
					this.SendPropertyChanging();
					this._Per_ApeMat = value;
					this.SendPropertyChanged("Per_ApeMat");
					this.OnPer_ApeMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_Email", Storage="_Per_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Per_Email
		{
			get
			{
				return this._Per_Email;
			}
			set
			{
				if ((this._Per_Email != value))
				{
					this.OnPer_EmailChanging(value);
					this.SendPropertyChanging();
					this._Per_Email = value;
					this.SendPropertyChanged("Per_Email");
					this.OnPer_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ExtTelefono", Storage="_Per_ExtTelefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Per_ExtTelefono
		{
			get
			{
				return this._Per_ExtTelefono;
			}
			set
			{
				if ((this._Per_ExtTelefono != value))
				{
					this.OnPer_ExtTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Per_ExtTelefono = value;
					this.SendPropertyChanged("Per_ExtTelefono");
					this.OnPer_ExtTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dep_ID", Storage="_Dep_ID", DbType="Int NOT NULL")]
		public int Dep_ID
		{
			get
			{
				return this._Dep_ID;
			}
			set
			{
				if ((this._Dep_ID != value))
				{
					this.OnDep_IDChanging(value);
					this.SendPropertyChanging();
					this._Dep_ID = value;
					this.SendPropertyChanged("Dep_ID");
					this.OnDep_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_IsActivo", Storage="_Per_IsActivo", DbType="Bit NOT NULL")]
		public bool Per_IsActivo
		{
			get
			{
				return this._Per_IsActivo;
			}
			set
			{
				if ((this._Per_IsActivo != value))
				{
					this.OnPer_IsActivoChanging(value);
					this.SendPropertyChanging();
					this._Per_IsActivo = value;
					this.SendPropertyChanged("Per_IsActivo");
					this.OnPer_IsActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_copia", Storage="_Per_copia", DbType="VarChar(350)")]
		public string Per_copia
		{
			get
			{
				return this._Per_copia;
			}
			set
			{
				if ((this._Per_copia != value))
				{
					this.OnPer_copiaChanging(value);
					this.SendPropertyChanging();
					this._Per_copia = value;
					this.SendPropertyChanged("Per_copia");
					this.OnPer_copiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Administrador", Storage="_Administradors", ThisKey="Per_ID", OtherKey="Per_ID")]
		public EntitySet<Administrador> Administradors
		{
			get
			{
				return this._Administradors;
			}
			set
			{
				this._Administradors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Comentario", Storage="_Comentarios", ThisKey="Per_ID", OtherKey="Per_ID")]
		public EntitySet<Comentario> Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				this._Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio", Storage="_Servicios", ThisKey="Per_ID", OtherKey="Per_ID_Levanto")]
		public EntitySet<Servicio> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio1", Storage="_Per_s", ThisKey="Per_ID", OtherKey="Per_ID_Atiende")]
		public EntitySet<Servicio> Per_s
		{
			get
			{
				return this._Per_s;
			}
			set
			{
				this._Per_s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Trabajador", Storage="_Trabajadors", ThisKey="Per_ID", OtherKey="Per_ID")]
		public EntitySet<Trabajador> Trabajadors
		{
			get
			{
				return this._Trabajadors;
			}
			set
			{
				this._Trabajadors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Usuarios", ThisKey="Per_ID", OtherKey="Per_ID")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Persona", Storage="_Departamento", ThisKey="Dep_ID", OtherKey="Dep_ID", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Personas.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Personas.Add(this);
						this._Dep_ID = value.Dep_ID;
					}
					else
					{
						this._Dep_ID = default(int);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Administradors(Administrador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Administradors(Administrador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Per_s(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Per_ID_AtiendePersona = this;
		}
		
		private void detach_Per_s(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Per_ID_AtiendePersona = null;
		}
		
		private void attach_Trabajadors(Trabajador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Trabajadors(Trabajador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicio")]
	public partial class Servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ser_ID;
		
		private int _Sere_ID;
		
		private int _Per_ID_Levanto;
		
		private System.Nullable<int> _Per_ID_Atiende;
		
		private string _Ser_Incidente;
		
		private System.DateTime _Ser_FechaIngreso;
		
		private System.DateTime _Ser_FechaUltimoE;
		
		private System.Nullable<int> _Ser_DeptoQueAtiende;
		
		private string _Ser_Area;
		
		private string _Ser_Equipo;
		
		private string _Ser_Nombre_Atiende;
		
		private System.Nullable<int> _Ser_Num_Fotos;
		
		private System.Nullable<System.DateTime> _Ser_FechaEstimadaFin;
		
		private string _Ser_Tipo;
		
		private EntitySet<Comentario> _Comentarios;
		
		private EntityRef<Departamento> _Departamento;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Persona> _Per_ID_AtiendePersona;
		
		private EntityRef<ServicioEstado> _ServicioEstado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSer_IDChanging(int value);
    partial void OnSer_IDChanged();
    partial void OnSere_IDChanging(int value);
    partial void OnSere_IDChanged();
    partial void OnPer_ID_LevantoChanging(int value);
    partial void OnPer_ID_LevantoChanged();
    partial void OnPer_ID_AtiendeChanging(System.Nullable<int> value);
    partial void OnPer_ID_AtiendeChanged();
    partial void OnSer_IncidenteChanging(string value);
    partial void OnSer_IncidenteChanged();
    partial void OnSer_FechaIngresoChanging(System.DateTime value);
    partial void OnSer_FechaIngresoChanged();
    partial void OnSer_FechaUltimoEChanging(System.DateTime value);
    partial void OnSer_FechaUltimoEChanged();
    partial void OnSer_DeptoQueAtiendeChanging(System.Nullable<int> value);
    partial void OnSer_DeptoQueAtiendeChanged();
    partial void OnSer_AreaChanging(string value);
    partial void OnSer_AreaChanged();
    partial void OnSer_EquipoChanging(string value);
    partial void OnSer_EquipoChanged();
    partial void OnSer_Nombre_AtiendeChanging(string value);
    partial void OnSer_Nombre_AtiendeChanged();
    partial void OnSer_Num_FotosChanging(System.Nullable<int> value);
    partial void OnSer_Num_FotosChanged();
    partial void OnSer_FechaEstimadaFinChanging(System.Nullable<System.DateTime> value);
    partial void OnSer_FechaEstimadaFinChanged();
    partial void OnSer_TipoChanging(string value);
    partial void OnSer_TipoChanged();
    #endregion
		
		public Servicio()
		{
			this._Comentarios = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentarios), new Action<Comentario>(this.detach_Comentarios));
			this._Departamento = default(EntityRef<Departamento>);
			this._Persona = default(EntityRef<Persona>);
			this._Per_ID_AtiendePersona = default(EntityRef<Persona>);
			this._ServicioEstado = default(EntityRef<ServicioEstado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_ID", Storage="_Ser_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Ser_ID
		{
			get
			{
				return this._Ser_ID;
			}
			set
			{
				if ((this._Ser_ID != value))
				{
					this.OnSer_IDChanging(value);
					this.SendPropertyChanging();
					this._Ser_ID = value;
					this.SendPropertyChanged("Ser_ID");
					this.OnSer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sere_ID", Storage="_Sere_ID", DbType="Int NOT NULL")]
		public int Sere_ID
		{
			get
			{
				return this._Sere_ID;
			}
			set
			{
				if ((this._Sere_ID != value))
				{
					this.OnSere_IDChanging(value);
					this.SendPropertyChanging();
					this._Sere_ID = value;
					this.SendPropertyChanged("Sere_ID");
					this.OnSere_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID_Levanto", Storage="_Per_ID_Levanto", DbType="Int NOT NULL")]
		public int Per_ID_Levanto
		{
			get
			{
				return this._Per_ID_Levanto;
			}
			set
			{
				if ((this._Per_ID_Levanto != value))
				{
					this.OnPer_ID_LevantoChanging(value);
					this.SendPropertyChanging();
					this._Per_ID_Levanto = value;
					this.SendPropertyChanged("Per_ID_Levanto");
					this.OnPer_ID_LevantoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID_Atiende", Storage="_Per_ID_Atiende", DbType="Int")]
		public System.Nullable<int> Per_ID_Atiende
		{
			get
			{
				return this._Per_ID_Atiende;
			}
			set
			{
				if ((this._Per_ID_Atiende != value))
				{
					this.OnPer_ID_AtiendeChanging(value);
					this.SendPropertyChanging();
					this._Per_ID_Atiende = value;
					this.SendPropertyChanged("Per_ID_Atiende");
					this.OnPer_ID_AtiendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_Incidente", Storage="_Ser_Incidente", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Ser_Incidente
		{
			get
			{
				return this._Ser_Incidente;
			}
			set
			{
				if ((this._Ser_Incidente != value))
				{
					this.OnSer_IncidenteChanging(value);
					this.SendPropertyChanging();
					this._Ser_Incidente = value;
					this.SendPropertyChanged("Ser_Incidente");
					this.OnSer_IncidenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_FechaIngreso", Storage="_Ser_FechaIngreso", DbType="DateTime NOT NULL")]
		public System.DateTime Ser_FechaIngreso
		{
			get
			{
				return this._Ser_FechaIngreso;
			}
			set
			{
				if ((this._Ser_FechaIngreso != value))
				{
					this.OnSer_FechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._Ser_FechaIngreso = value;
					this.SendPropertyChanged("Ser_FechaIngreso");
					this.OnSer_FechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_FechaUltimoE", Storage="_Ser_FechaUltimoE", DbType="DateTime NOT NULL")]
		public System.DateTime Ser_FechaUltimoE
		{
			get
			{
				return this._Ser_FechaUltimoE;
			}
			set
			{
				if ((this._Ser_FechaUltimoE != value))
				{
					this.OnSer_FechaUltimoEChanging(value);
					this.SendPropertyChanging();
					this._Ser_FechaUltimoE = value;
					this.SendPropertyChanged("Ser_FechaUltimoE");
					this.OnSer_FechaUltimoEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_DeptoQueAtiende", Storage="_Ser_DeptoQueAtiende", DbType="Int")]
		public System.Nullable<int> Ser_DeptoQueAtiende
		{
			get
			{
				return this._Ser_DeptoQueAtiende;
			}
			set
			{
				if ((this._Ser_DeptoQueAtiende != value))
				{
					this.OnSer_DeptoQueAtiendeChanging(value);
					this.SendPropertyChanging();
					this._Ser_DeptoQueAtiende = value;
					this.SendPropertyChanged("Ser_DeptoQueAtiende");
					this.OnSer_DeptoQueAtiendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_Area", Storage="_Ser_Area", DbType="VarChar(50)")]
		public string Ser_Area
		{
			get
			{
				return this._Ser_Area;
			}
			set
			{
				if ((this._Ser_Area != value))
				{
					this.OnSer_AreaChanging(value);
					this.SendPropertyChanging();
					this._Ser_Area = value;
					this.SendPropertyChanged("Ser_Area");
					this.OnSer_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_Equipo", Storage="_Ser_Equipo", DbType="VarChar(50)")]
		public string Ser_Equipo
		{
			get
			{
				return this._Ser_Equipo;
			}
			set
			{
				if ((this._Ser_Equipo != value))
				{
					this.OnSer_EquipoChanging(value);
					this.SendPropertyChanging();
					this._Ser_Equipo = value;
					this.SendPropertyChanged("Ser_Equipo");
					this.OnSer_EquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_Nombre_Atiende", Storage="_Ser_Nombre_Atiende", DbType="VarChar(50)")]
		public string Ser_Nombre_Atiende
		{
			get
			{
				return this._Ser_Nombre_Atiende;
			}
			set
			{
				if ((this._Ser_Nombre_Atiende != value))
				{
					this.OnSer_Nombre_AtiendeChanging(value);
					this.SendPropertyChanging();
					this._Ser_Nombre_Atiende = value;
					this.SendPropertyChanged("Ser_Nombre_Atiende");
					this.OnSer_Nombre_AtiendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_Num_Fotos", Storage="_Ser_Num_Fotos", DbType="Int")]
		public System.Nullable<int> Ser_Num_Fotos
		{
			get
			{
				return this._Ser_Num_Fotos;
			}
			set
			{
				if ((this._Ser_Num_Fotos != value))
				{
					this.OnSer_Num_FotosChanging(value);
					this.SendPropertyChanging();
					this._Ser_Num_Fotos = value;
					this.SendPropertyChanged("Ser_Num_Fotos");
					this.OnSer_Num_FotosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_FechaEstimadaFin", Storage="_Ser_FechaEstimadaFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ser_FechaEstimadaFin
		{
			get
			{
				return this._Ser_FechaEstimadaFin;
			}
			set
			{
				if ((this._Ser_FechaEstimadaFin != value))
				{
					this.OnSer_FechaEstimadaFinChanging(value);
					this.SendPropertyChanging();
					this._Ser_FechaEstimadaFin = value;
					this.SendPropertyChanged("Ser_FechaEstimadaFin");
					this.OnSer_FechaEstimadaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ser_Tipo", DbType="Char(10)")]
		public string Ser_Tipo
		{
			get
			{
				return this._Ser_Tipo;
			}
			set
			{
				if ((this._Ser_Tipo != value))
				{
					this.OnSer_TipoChanging(value);
					this.SendPropertyChanging();
					this._Ser_Tipo = value;
					this.SendPropertyChanged("Ser_Tipo");
					this.OnSer_TipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicio_Comentario", Storage="_Comentarios", ThisKey="Ser_ID", OtherKey="Ser_ID")]
		public EntitySet<Comentario> Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				this._Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Servicio", Storage="_Departamento", ThisKey="Ser_DeptoQueAtiende", OtherKey="Dep_ID", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._Ser_DeptoQueAtiende = value.Dep_ID;
					}
					else
					{
						this._Ser_DeptoQueAtiende = default(Nullable<int>);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio", Storage="_Persona", ThisKey="Per_ID_Levanto", OtherKey="Per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._Per_ID_Levanto = value.Per_ID;
					}
					else
					{
						this._Per_ID_Levanto = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio1", Storage="_Per_ID_AtiendePersona", ThisKey="Per_ID_Atiende", OtherKey="Per_ID", IsForeignKey=true)]
		public Persona Per_ID_AtiendePersona
		{
			get
			{
				return this._Per_ID_AtiendePersona.Entity;
			}
			set
			{
				Persona previousValue = this._Per_ID_AtiendePersona.Entity;
				if (((previousValue != value) 
							|| (this._Per_ID_AtiendePersona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Per_ID_AtiendePersona.Entity = null;
						previousValue.Per_s.Remove(this);
					}
					this._Per_ID_AtiendePersona.Entity = value;
					if ((value != null))
					{
						value.Per_s.Add(this);
						this._Per_ID_Atiende = value.Per_ID;
					}
					else
					{
						this._Per_ID_Atiende = default(Nullable<int>);
					}
					this.SendPropertyChanged("Per_ID_AtiendePersona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ServicioEstado_Servicio", Storage="_ServicioEstado", ThisKey="Sere_ID", OtherKey="Sere_ID", IsForeignKey=true)]
		public ServicioEstado ServicioEstado
		{
			get
			{
				return this._ServicioEstado.Entity;
			}
			set
			{
				ServicioEstado previousValue = this._ServicioEstado.Entity;
				if (((previousValue != value) 
							|| (this._ServicioEstado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ServicioEstado.Entity = null;
						previousValue.Servicios.Remove(this);
					}
					this._ServicioEstado.Entity = value;
					if ((value != null))
					{
						value.Servicios.Add(this);
						this._Sere_ID = value.Sere_ID;
					}
					else
					{
						this._Sere_ID = default(int);
					}
					this.SendPropertyChanged("ServicioEstado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = this;
		}
		
		private void detach_Comentarios(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServicioEstado")]
	public partial class ServicioEstado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Sere_ID;
		
		private string _Sere_Clave;
		
		private string _Sere_Descripcion;
		
		private EntitySet<Servicio> _Servicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSere_IDChanging(int value);
    partial void OnSere_IDChanged();
    partial void OnSere_ClaveChanging(string value);
    partial void OnSere_ClaveChanged();
    partial void OnSere_DescripcionChanging(string value);
    partial void OnSere_DescripcionChanged();
    #endregion
		
		public ServicioEstado()
		{
			this._Servicios = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicios), new Action<Servicio>(this.detach_Servicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sere_ID", Storage="_Sere_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Sere_ID
		{
			get
			{
				return this._Sere_ID;
			}
			set
			{
				if ((this._Sere_ID != value))
				{
					this.OnSere_IDChanging(value);
					this.SendPropertyChanging();
					this._Sere_ID = value;
					this.SendPropertyChanged("Sere_ID");
					this.OnSere_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sere_Clave", Storage="_Sere_Clave", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Sere_Clave
		{
			get
			{
				return this._Sere_Clave;
			}
			set
			{
				if ((this._Sere_Clave != value))
				{
					this.OnSere_ClaveChanging(value);
					this.SendPropertyChanging();
					this._Sere_Clave = value;
					this.SendPropertyChanged("Sere_Clave");
					this.OnSere_ClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sere_Descripcion", Storage="_Sere_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Sere_Descripcion
		{
			get
			{
				return this._Sere_Descripcion;
			}
			set
			{
				if ((this._Sere_Descripcion != value))
				{
					this.OnSere_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._Sere_Descripcion = value;
					this.SendPropertyChanged("Sere_Descripcion");
					this.OnSere_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ServicioEstado_Servicio", Storage="_Servicios", ThisKey="Sere_ID", OtherKey="Sere_ID")]
		public EntitySet<Servicio> Servicios
		{
			get
			{
				return this._Servicios;
			}
			set
			{
				this._Servicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.ServicioEstado = this;
		}
		
		private void detach_Servicios(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.ServicioEstado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServTipoCat")]
	public partial class ServTipoCat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Ser_ID;
		
		private System.Nullable<int> _IdServ;
		
		private System.Nullable<int> _IdCate;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSer_IDChanging(System.Nullable<int> value);
    partial void OnSer_IDChanged();
    partial void OnIdServChanging(System.Nullable<int> value);
    partial void OnIdServChanged();
    partial void OnIdCateChanging(System.Nullable<int> value);
    partial void OnIdCateChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public ServTipoCat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ser_ID", Storage="_Ser_ID", DbType="Int")]
		public System.Nullable<int> Ser_ID
		{
			get
			{
				return this._Ser_ID;
			}
			set
			{
				if ((this._Ser_ID != value))
				{
					this.OnSer_IDChanging(value);
					this.SendPropertyChanging();
					this._Ser_ID = value;
					this.SendPropertyChanged("Ser_ID");
					this.OnSer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="idServ", Storage="_IdServ", DbType="Int")]
		public System.Nullable<int> IdServ
		{
			get
			{
				return this._IdServ;
			}
			set
			{
				if ((this._IdServ != value))
				{
					this.OnIdServChanging(value);
					this.SendPropertyChanging();
					this._IdServ = value;
					this.SendPropertyChanged("IdServ");
					this.OnIdServChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="idCate", Storage="_IdCate", DbType="Int")]
		public System.Nullable<int> IdCate
		{
			get
			{
				return this._IdCate;
			}
			set
			{
				if ((this._IdCate != value))
				{
					this.OnIdCateChanging(value);
					this.SendPropertyChanging();
					this._IdCate = value;
					this.SendPropertyChanged("IdCate");
					this.OnIdCateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="fecha", Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trabajador")]
	public partial class Trabajador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tra_ID;
		
		private int _Per_ID;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTra_IDChanging(int value);
    partial void OnTra_IDChanged();
    partial void OnPer_IDChanging(int value);
    partial void OnPer_IDChanged();
    #endregion
		
		public Trabajador()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tra_ID", Storage="_Tra_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tra_ID
		{
			get
			{
				return this._Tra_ID;
			}
			set
			{
				if ((this._Tra_ID != value))
				{
					this.OnTra_IDChanging(value);
					this.SendPropertyChanging();
					this._Tra_ID = value;
					this.SendPropertyChanged("Tra_ID");
					this.OnTra_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID", Storage="_Per_ID", DbType="Int NOT NULL")]
		public int Per_ID
		{
			get
			{
				return this._Per_ID;
			}
			set
			{
				if ((this._Per_ID != value))
				{
					this.OnPer_IDChanging(value);
					this.SendPropertyChanging();
					this._Per_ID = value;
					this.SendPropertyChanged("Per_ID");
					this.OnPer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Trabajador", Storage="_Persona", ThisKey="Per_ID", OtherKey="Per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Trabajadors.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Trabajadors.Add(this);
						this._Per_ID = value.Per_ID;
					}
					else
					{
						this._Per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Usu_ID;
		
		private string _Usu_Usuario;
		
		private string _Usu_Password;
		
		private int _Per_ID;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsu_IDChanging(int value);
    partial void OnUsu_IDChanged();
    partial void OnUsu_UsuarioChanging(string value);
    partial void OnUsu_UsuarioChanged();
    partial void OnUsu_PasswordChanging(string value);
    partial void OnUsu_PasswordChanged();
    partial void OnPer_IDChanging(int value);
    partial void OnPer_IDChanged();
    #endregion
		
		public Usuario()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usu_ID", Storage="_Usu_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Usu_ID
		{
			get
			{
				return this._Usu_ID;
			}
			set
			{
				if ((this._Usu_ID != value))
				{
					this.OnUsu_IDChanging(value);
					this.SendPropertyChanging();
					this._Usu_ID = value;
					this.SendPropertyChanged("Usu_ID");
					this.OnUsu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usu_Usuario", Storage="_Usu_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usu_Usuario
		{
			get
			{
				return this._Usu_Usuario;
			}
			set
			{
				if ((this._Usu_Usuario != value))
				{
					this.OnUsu_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usu_Usuario = value;
					this.SendPropertyChanged("Usu_Usuario");
					this.OnUsu_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usu_Password", Storage="_Usu_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usu_Password
		{
			get
			{
				return this._Usu_Password;
			}
			set
			{
				if ((this._Usu_Password != value))
				{
					this.OnUsu_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Usu_Password = value;
					this.SendPropertyChanged("Usu_Password");
					this.OnUsu_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="per_ID", Storage="_Per_ID", DbType="Int NOT NULL")]
		public int Per_ID
		{
			get
			{
				return this._Per_ID;
			}
			set
			{
				if ((this._Per_ID != value))
				{
					this.OnPer_IDChanging(value);
					this.SendPropertyChanging();
					this._Per_ID = value;
					this.SendPropertyChanged("Per_ID");
					this.OnPer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Persona", ThisKey="Per_ID", OtherKey="Per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._Per_ID = value.Per_ID;
					}
					else
					{
						this._Per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_Get_ServiciosAsignadosResult
	{
		
		private int _ID;
		
		private string _Nombre;
		
		private string _Incidente;
		
		private string _Comentarios;
		
		private string _Asignado_A;
		
		private System.Nullable<System.DateTime> _Fecha_Estimada_Fin;
		
		private System.DateTime _Fecha_Ingreso;
		
		private System.DateTime _Ultimo_Estado;
		
		public sp_Get_ServiciosAsignadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				if ((this._Comentarios != value))
				{
					this._Comentarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignado_A", DbType="VarChar(50)")]
		public string Asignado_A
		{
			get
			{
				return this._Asignado_A;
			}
			set
			{
				if ((this._Asignado_A != value))
				{
					this._Asignado_A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Estimada_Fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Estimada_Fin
		{
			get
			{
				return this._Fecha_Estimada_Fin;
			}
			set
			{
				if ((this._Fecha_Estimada_Fin != value))
				{
					this._Fecha_Estimada_Fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Ingreso
		{
			get
			{
				return this._Fecha_Ingreso;
			}
			set
			{
				if ((this._Fecha_Ingreso != value))
				{
					this._Fecha_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultimo_Estado", DbType="DateTime NOT NULL")]
		public System.DateTime Ultimo_Estado
		{
			get
			{
				return this._Ultimo_Estado;
			}
			set
			{
				if ((this._Ultimo_Estado != value))
				{
					this._Ultimo_Estado = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosAsignadosMResult
	{
		
		private int _ID;
		
		private string _Nombre;
		
		private string _Incidente;
		
		private string _Area;
		
		private string _Equipo;
		
		private string _Comentarios;
		
		private string _Responsable;
		
		private System.Nullable<System.DateTime> _Fecha_Estimada_Fin;
		
		private System.DateTime _Fecha_Ingreso;
		
		private System.DateTime _Ultimo_Estado;
		
		public sp_Get_ServiciosAsignadosMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo", DbType="VarChar(50)")]
		public string Equipo
		{
			get
			{
				return this._Equipo;
			}
			set
			{
				if ((this._Equipo != value))
				{
					this._Equipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				if ((this._Comentarios != value))
				{
					this._Comentarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsable", DbType="VarChar(50)")]
		public string Responsable
		{
			get
			{
				return this._Responsable;
			}
			set
			{
				if ((this._Responsable != value))
				{
					this._Responsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Estimada_Fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Estimada_Fin
		{
			get
			{
				return this._Fecha_Estimada_Fin;
			}
			set
			{
				if ((this._Fecha_Estimada_Fin != value))
				{
					this._Fecha_Estimada_Fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Ingreso
		{
			get
			{
				return this._Fecha_Ingreso;
			}
			set
			{
				if ((this._Fecha_Ingreso != value))
				{
					this._Fecha_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultimo_Estado", DbType="DateTime NOT NULL")]
		public System.DateTime Ultimo_Estado
		{
			get
			{
				return this._Ultimo_Estado;
			}
			set
			{
				if ((this._Ultimo_Estado != value))
				{
					this._Ultimo_Estado = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosFinalizadosResult
	{
		
		private int _ID;
		
		private int _Usuario;
		
		private string _Nombre;
		
		private string _Incidente;
		
		private string _Comentarios;
		
		private string _Asignado_A;
		
		private string _Estado;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private System.DateTime _Fecha_de_último_Estado;
		
		private string _Duración;
		
		private string _CumplimientoCalidad;
		
		public sp_Get_ServiciosFinalizadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="Int NOT NULL")]
		public int Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(200)")]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				if ((this._Comentarios != value))
				{
					this._Comentarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asignado_A", DbType="VarChar(50)")]
		public string Asignado_A
		{
			get
			{
				return this._Asignado_A;
			}
			set
			{
				if ((this._Asignado_A != value))
				{
					this._Asignado_A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de último Estado]", Storage="_Fecha_de_último_Estado", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_último_Estado
		{
			get
			{
				return this._Fecha_de_último_Estado;
			}
			set
			{
				if ((this._Fecha_de_último_Estado != value))
				{
					this._Fecha_de_último_Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duración", DbType="VarChar(36)")]
		public string Duración
		{
			get
			{
				return this._Duración;
			}
			set
			{
				if ((this._Duración != value))
				{
					this._Duración = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CumplimientoCalidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CumplimientoCalidad
		{
			get
			{
				return this._CumplimientoCalidad;
			}
			set
			{
				if ((this._CumplimientoCalidad != value))
				{
					this._CumplimientoCalidad = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosFinalizadosMResult
	{
		
		private int _ID;
		
		private int _Usuario;
		
		private string _Nombre;
		
		private string _Incidente;
		
		private string _Area;
		
		private string _Equipo;
		
		private string _Comentarios;
		
		private string _Responsable;
		
		private string _Estado;
		
		private System.DateTime _Fecha_Ingreso;
		
		private System.DateTime _Fecha_Estimada_Fin;
		
		private string _Duración;
		
		public sp_Get_ServiciosFinalizadosMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="Int NOT NULL")]
		public int Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(200)")]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo", DbType="VarChar(50)")]
		public string Equipo
		{
			get
			{
				return this._Equipo;
			}
			set
			{
				if ((this._Equipo != value))
				{
					this._Equipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				if ((this._Comentarios != value))
				{
					this._Comentarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsable", DbType="VarChar(50)")]
		public string Responsable
		{
			get
			{
				return this._Responsable;
			}
			set
			{
				if ((this._Responsable != value))
				{
					this._Responsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Ingreso
		{
			get
			{
				return this._Fecha_Ingreso;
			}
			set
			{
				if ((this._Fecha_Ingreso != value))
				{
					this._Fecha_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Estimada_Fin", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Estimada_Fin
		{
			get
			{
				return this._Fecha_Estimada_Fin;
			}
			set
			{
				if ((this._Fecha_Estimada_Fin != value))
				{
					this._Fecha_Estimada_Fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duración", DbType="VarChar(36)")]
		public string Duración
		{
			get
			{
				return this._Duración;
			}
			set
			{
				if ((this._Duración != value))
				{
					this._Duración = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosSolicitadosResult
	{
		
		private int _ID;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private string _Nombre;
		
		private string _Asignado_A;
		
		private string _Incidente;
		
		private string _Estado;
		
		public sp_Get_ServiciosSolicitadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Asignado A]", Storage="_Asignado_A", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Asignado_A
		{
			get
			{
				return this._Asignado_A;
			}
			set
			{
				if ((this._Asignado_A != value))
				{
					this._Asignado_A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosSolicitadosMResult
	{
		
		private int _ID;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private string _Nombre;
		
		private string _Responsable;
		
		private string _Incidente;
		
		private string _Area;
		
		private string _Equipo;
		
		private string _Estado;
		
		public sp_Get_ServiciosSolicitadosMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsable", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Responsable
		{
			get
			{
				return this._Responsable;
			}
			set
			{
				if ((this._Responsable != value))
				{
					this._Responsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo", DbType="VarChar(50)")]
		public string Equipo
		{
			get
			{
				return this._Equipo;
			}
			set
			{
				if ((this._Equipo != value))
				{
					this._Equipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class spTicketsConsultaResult
	{
		
		private System.Nullable<int> _Total;
		
		public spTicketsConsultaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class spTicketsConsultaMantoResult
	{
		
		private System.Nullable<int> _Total;
		
		public spTicketsConsultaMantoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
